"use strict";
const CONFIG={invitationUrl:"https://mya2026.galaxymanager.systems/",weddingDate:new Date("2026-10-24T16:30:00-06:00"),invitadosUrl:"invitados.json"};
const normalizeText=(v)=>String(v||"").trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\s+/g," ");
let invitadosCache=[];
async function cargarInvitados(){if(invitadosCache.length)return invitadosCache;const r=await fetch(CONFIG.invitadosUrl,{cache:"no-store"});if(!r.ok)throw new Error("No se pudo cargar invitados.json");invitadosCache=await r.json();return invitadosCache}
function setMessage(t,type=""){const m=document.getElementById("mensajeBusqueda");m.textContent=t;m.className=`form-message ${type}`.trim()}
function validarBusqueda(v){const x=v.trim();if(!x)return"Escribe tu nombre completo o código de invitación.";if(x.length<3)return"Escribe al menos 3 caracteres.";if(/[<>]/.test(x))return"El texto contiene caracteres no válidos.";return""}
function buscarCoincidencias(invitados,valor){const q=normalizeText(valor);return invitados.filter(inv=>{const n=normalizeText(inv.nombre),c=normalizeText(inv.codigo);return c===q||n.includes(q)||q.split(" ").every(p=>n.includes(p))})}
function generarOpciones(max){let h="";for(let i=1;i<=Number(max);i++)h+=`<option value="${i}">${i} ${i===1?"persona":"personas"}</option>`;return h}
function mostrarListaCoincidencias(coincidencias){document.getElementById("resultado").innerHTML=`<div class="ticket"><div class="ticket-main"><h3>Selecciona tu invitación</h3><p class="ticket-info">Encontramos varias coincidencias. Elige la correcta:</p><div class="cta-row" style="justify-content:flex-start">${coincidencias.map((inv,i)=>`<button class="btn ghost" type="button" onclick="mostrarPasePorIndice(${i})">${inv.nombre} · ${inv.codigo}</button>`).join("")}</div></div></div>`;window.__coincidencias=coincidencias}
window.mostrarPasePorIndice=function(i){const inv=window.__coincidencias[i];if(inv)mostrarPase(inv)};
function mostrarPase(inv){setMessage("Invitación localizada.","ok");const guardado=JSON.parse(localStorage.getItem(`rsvp_${inv.codigo}`)||"null");const txt=guardado?`Asistencia confirmada: ${guardado.asistentes} ${Number(guardado.asistentes)===1?"persona":"personas"}.`:"";document.getElementById("resultado").innerHTML=`<article class="ticket"><div class="ticket-main"><h3>Pase personalizado</h3><div class="ticket-name">${inv.nombre}</div><div class="ticket-info">Código: <strong>${inv.codigo}</strong><br>Invitación válida para <strong>${inv.pases}</strong> ${Number(inv.pases)===1?"persona":"personas"}<br>Mesa: <strong>${inv.mesa||"Por asignar"}</strong></div></div><div class="confirm-box"><label for="asistentes">¿Cuántas personas asistirán?</label><select id="asistentes">${generarOpciones(inv.pases)}</select><button class="btn gold" type="button" onclick="confirmarAsistencia('${inv.codigo}','${encodeURIComponent(inv.nombre)}')">Confirmar asistencia</button><div id="estado" class="confirm-status">${txt}</div></div><div class="ticket-seal">M&A</div></article>`}
window.confirmarAsistencia=function(codigo,nombreCodificado){const asistentes=document.getElementById("asistentes").value;const nombre=decodeURIComponent(nombreCodificado);const reg={codigo,nombre,asistentes:Number(asistentes),fecha:new Date().toISOString()};localStorage.setItem(`rsvp_${codigo}`,JSON.stringify(reg));document.getElementById("estado").textContent=`Asistencia confirmada: ${asistentes} ${Number(asistentes)===1?"persona":"personas"}.`;console.log("RSVP temporal:",reg)};
async function manejarBusqueda(e){e.preventDefault();const input=document.getElementById("buscar");const err=validarBusqueda(input.value);if(err){setMessage(err,"error");document.getElementById("resultado").innerHTML="";return}try{setMessage("Buscando invitación...");const invitados=await cargarInvitados();const c=buscarCoincidencias(invitados,input.value);if(!c.length){setMessage("No encontramos esa invitación. Revisa tu nombre completo o código.","error");document.getElementById("resultado").innerHTML="";return}if(c.length===1)mostrarPase(c[0]);else{setMessage("Encontramos varias coincidencias.");mostrarListaCoincidencias(c)}}catch(err){setMessage("No se pudo cargar la lista. Revisa invitados.json.","error");console.error(err)}}
function initTabs(){document.querySelectorAll(".tab-btn").forEach(btn=>btn.addEventListener("click",()=>{const t=btn.dataset.tab;document.querySelectorAll(".tab-btn").forEach(b=>b.classList.remove("active"));document.querySelectorAll(".tab-panel").forEach(p=>p.classList.remove("active"));btn.classList.add("active");document.getElementById(`tab-${t}`)?.classList.add("active")}))}
function initShare(){document.getElementById("shareBtn")?.addEventListener("click",async()=>{const d={title:"Montserrat & Alan | Nuestra boda",text:"Te invitamos a celebrar nuestra boda.",url:CONFIG.invitationUrl};try{if(navigator.share)await navigator.share(d);else{await navigator.clipboard.writeText(CONFIG.invitationUrl);alert("Enlace copiado.")}}catch(_){}})}
function initCountdown(){const e=Object.fromEntries(["days","hours","minutes","seconds"].map(id=>[id,document.getElementById(id)]));function u(){const diff=Math.max(0,CONFIG.weddingDate-new Date());e.days.textContent=Math.floor(diff/86400000);e.hours.textContent=String(Math.floor(diff%86400000/3600000)).padStart(2,"0");e.minutes.textContent=String(Math.floor(diff%3600000/60000)).padStart(2,"0");e.seconds.textContent=String(Math.floor(diff%60000/1000)).padStart(2,"0")}u();setInterval(u,1000)}
function initPetals(){if(matchMedia("(prefers-reduced-motion: reduce)").matches)return;setInterval(()=>{const p=document.createElement("span");p.className="floating-petal";p.style.zIndex="9999";p.style.left=`${Math.random()*100}vw`;p.style.setProperty("--x",`${Math.random()*160-80}px`);p.style.animationDuration=`${7+Math.random()*6}s`;document.body.appendChild(p);setTimeout(()=>p.remove(),14000)},1000)}
document.addEventListener("DOMContentLoaded",()=>{document.getElementById("formBusqueda")?.addEventListener("submit",manejarBusqueda);initTabs();initShare();initCountdown();initPetals()});

